### ISSUE TITLE
Release 0.10.1

### ISSUE THREAD

**Issue by allejo** [allejo/bzion#150]
Let's start planning what will be included in the next planned release. These are things that I couldn't complete for 0.10.0 because I ran out of time.

- [ ] Messages UI needs to be rewritten/updated (#168)
  - [ ] Remove/update legacy JS
  - [ ] Improve mobile-friendliness
- [x] Introduce sandbox configuration option (#149)
- [ ] Improve/fix Elo recalculations and deletions (#170)
- [ ] High-contrast theme (#169)

I'd like to move to a quicker release schedule. So more releases with small improvements instead of a monolithic new release once a year.

**Comment by allejo** [comment]
Let's lock down the **0.10.1** milestone and only work on what's been tagged for this release on or before November 1st. [Here's our ship list](https://github.com/allejo/bzion/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20milestone%3A%22Version%200.10.1%22%20created%3A%3C%3D2017-11-01) for **0.10.1**.

**Comment by allejo** [comment]
Individual issues have been created for the task list above and have been triaged into appropriate milestones. Closing
